spring:
  application:
    name: sast
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.22.241.45:3306/SAST_ToDo
    username: skr
    password: skr

server:
  port: 8081
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
##输出mybatis日志信息到控制台